set pia=%fileno:~0,4%
set pia1=%fileno:~0,4%1
set fileno=%fileno:~0,12%
set birthdate=%birthdate: =%
set passport_no=%passport_no: =%

set today=%date:~7,2%/%date:~4,2%/%date:~10,4%
if /i %pia% EQU BGDD set aptdate=03/04/2016
if /i %pia% EQU BGDC set aptdate=03/04/2016
if /i %pia% EQU BGDR set aptdate=06/04/2016


echo ##################################################################
echo ++++ pia ============ %pia% ++++++++++ pia1 =========== %pia1%  
echo -----------------------------------------------------------------
echo ++++ fileno ========= "%fileno%"
echo ++++ APPLNAME ======= "%APPLNAME%"
echo ++++ birthdate ====== "%birthdate%"
echo ++++ passport_no ==== "%passport_no%"
echo -----------------------------------------------------------------
echo ++++ today ========== %today% ++++ apptdate ======= %aptdate%   
echo ##################################################################
echo ##################################################################

:StartBegin
SET /a try=0
SET /a sn=0
SET /a cap=4
SET /a useProxy=0
SET /a usedante=0
SET /a difftime=300
SET socks5=
SET /a cn=%RANDOM%*8/32768
SET /a rn=%RANDOM%*20/32768
SET /a _rand=%RANDOM%*100/32768+151
SET /a sessionstatus=0
TITLE IVAC %~n0  ##%fileno%##%APPLNAME%##%pia%##%pia1%##CN : %cn% _ RN:  %rn% _ TRY : %try%

:checktime 
set startTime=%time%	
SET /a ms=%RANDOM%*98/32768+1
set endTime=11:58:07.%ms%	

echo startTime: %startTime%	
echo endTime:   %endTime%	
	
set /a sth=%startTime:~0,2%	
set /a stm=1%startTime:~3,2% - 100	
set /a sts=1%startTime:~6,2% - 100	
	
set /a eth=%endTime:~0,2%	
set /a etm=1%endTime:~3,2% - 100	
set /a ets=1%endTime:~6,2% - 100	
	
set /a lth=0	
set /a ltm=0	
set /a lts=0	
	
:CHECK_SEC	
if /i %ets% LSS %sts% goto ROLL_MIN	
set /a lts=%ets% - %sts%	
goto CHECK_MIN	
	
:ROLL_MIN	
set /a stm+=1	
set /a lts=%ets% + 60 - %sts%	
	
:CHECK_MIN	
if /i %etm% LSS %stm% goto ROLL_HOUR	
set /a ltm=%etm% - %stm%	
goto CHECK_HOUR	
	
:ROLL_HOUR	
set /a sth+=1	
set /a ltm=%etm% + 60 - %stm%	
	
:CHECK_HOUR	
if /i %eth% LSS %sth% goto ROLL_DAY	
set /a lth=%eth% - %sth%	
goto DONE	
	
:ROLL_DAY	
set /a lth=%eth% + 24 - %sth%	
	
	
:DONE	
if /i %lts% GTR 59 (	
  set lts%%=60	
  set ltm+=1	
)	
	
if /i %ltm% GTR 59 (	
  set ltm%%=60	
  set lth+=1	
)	
	
echo Lapsed hours:   %lth%	
echo Lapsed minutes: %ltm%	
echo Lapsed seconds: %lts%	
set /a tls = %lth% * 60 * 60 + %ltm% * 60 + %lts%	
	
if /i %tls% GTR 16000 goto BeginGenerateOTP

echo Total Lapsed Seconds: %tls%	
timeout %tls%	
goto BeginGenerateOTP	
echo ****************** Technical Problem at Line Number 120 ****************** >> %fileno%-report.txt	

:BeginGenerateOTP
color 02
TITLE IVAC %~n0  ##   STEP1 _ CN : %cn% _ RN:  %rn% _ TRY : %try%
SET /a _rand=%RANDOM%*100/32768+151 & SET socks5=--socks5 103.239.6.%_rand%:1080 --proxy-user danteproxy:dantepass


:GenerateOTP
c:\curl\curl%cn% --fail --silent --show-error http://103.239.6.135/ivac/allotmentsave/show.php?passport_no=%passport_no% -o %fileno%-status.txt -w "Check Allotment Save Status \n"
IF EXIST "%fileno%-status.txt" FOR /F %%d IN (%fileno%-status.txt) DO SET status=%%d
del %fileno%-status.txt
SET status=%status:~0,1%
IF /i %status% EQU Y color 09 & echo File Already Taken & timeout 5 & goto EXIT

c:\curl\curl%cn% --fail --silent --show-error http://103.239.6.135/ivac/otp/show.php?fileno=%fileno% -o %fileno%-otp.txt -w "Check OTP Save Status \n"
c:\curl\curl%cn% -sS http://103.239.6.135/ivac/otp/difftime.php?fileno=%fileno% -o %fileno%-difftime.txt -w "Check difftime Save Status \n"
IF EXIST "%fileno%-difftime.txt" FOR /F %%d IN (%fileno%-difftime.txt) DO SET difftime=%%d
del %fileno%-difftime.txt
IF /i %difftime% GTR 180 goto Appointment_Login_otp

FOR /F %%o IN (%fileno%-otp.txt) DO (
SET otp=%%o
del %fileno%-otp.txt
IF otp EQU nootp goto Appointment_Login_otp
echo *********** OTP GENERATED by Another Script %difftime% ********* >> %fileno%-report.txt
goto BeginProcessApptPwd
)


:Appointment_Login_otp
SET /a try+=1
if /i %try% GTR 5 SET /a _rand=%RANDOM%*100/32768+151 & set /a try=0 & SET socks5=--socks5 103.239.6.%_rand%:1080 --proxy-user danteproxy:dantepass

echo ###################### STEP APPOINTMENT_LOGIN1 curl version %cn% _ time %time% _ RN:  %rn% _  TRY : %try% ################## >> %fileno%-report.txt
c:\curl\curl%cn% -v --trace-time -S --connect-timeout 3 -m 5 -b otpcookie%rn%.txt -c %fileno%_cookie.txt %socks5% -H "Keep-Alive: 60" -H "Connection: keep-alive" --dump-header %fileno%-Appointment_headers1.txt --user-agent "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0" --referer http://indianvisa-bangladesh.nic.in/visa/index.html http://indianvisa-bangladesh.nic.in/visa/Appointment_Login.jsp --max-redirs 5 -L -o %fileno%-Appointment_Login1.txt -w "STEP ONE.ONE Appointment_Login OTP Processing on %time% by %try% \n" 2>> %fileno%-report.txt	

findstr /L /O /N /C:"HTTP/1.1 200 OK" %fileno%-Appointment_headers1.txt
if /i %ERRORLEVEL% EQU 0 echo ********************** Error Level is %ERRORLEVEL% for 200===BeginGenerateOTP=== & goto Appointment_Login_otp200 

findstr /L /O /N /C:"HTTP/1.1 404 Not Found" %fileno%-Appointment_headers1.txt
if /i %ERRORLEVEL% EQU 0 goto BeginGenerateOTP 

findstr /L /O /N /C:"HTTP/1.1 302 Moved Temporarily" %fileno%-Appointment_headers1.txt
if /i %ERRORLEVEL% EQU 0 echo ********************** Error Level is %ERRORLEVEL% for 302===BeginGenerateOTP=== & goto BeginGenerateOTP 

echo ********************** SERVER BUSY === Retry Again ===STEP ONE.ONE=== >> %fileno%-report.txt
if /i %try% EQU 30 set try=0 & goto BeginGenerateOTP
goto Appointment_Login_otp
echo ************************* Technical Problem ***************************** >> %fileno%-report.txt

:Appointment_Login_otp200
findstr /L /O /N /C:"The Problem may be due to 500 Server Error/404 Page Not Found" %fileno%-Appointment_Login1.txt
if /i %ERRORLEVEL% EQU 0 echo ======   Error Level is %ERRORLEVEL% for ===500 Server Error/404 Page Not Found=== & goto Appointment_Login_otp

findstr /L /O /N /C:"Appointment not started. Please try again after some time" %fileno%-Appointment_Login1.txt
if /i %ERRORLEVEL% EQU 0 echo ======   Error Level is %ERRORLEVEL% for ===OTP can be generated only after appointment time starts=== & timeout 2 & goto checktime

findstr /L /O /N /C:"Connection: Close" %fileno%-Appointment_headers1.txt
if /i %ERRORLEVEL% EQU 0 call :captchaenable & goto Appointment_Login_otp

:checkGenerateOTP1
@echo off & setlocal EnableDelayedExpansion
for /F "delims=" %%j in ('type "%fileno%-Appointment_Login1.txt"') do (
  set /A counter+=1
  if !counter! equ 119 (echo.%%j> "%fileno%-Appointment_firstvar1.txt")
  if !counter! equ 120 (echo.%%j>> "%fileno%-Appointment_firstvar1.txt")
  if !counter! equ 121 (echo.%%j>> "%fileno%-Appointment_firstvar1.txt")
  if !counter! equ 122 (echo.%%j>> "%fileno%-Appointment_firstvar1.txt")
  if !counter! equ 123 (echo.%%j>> "%fileno%-Appointment_firstvar1.txt")
  if !counter! equ 124 (echo.%%j>> "%fileno%-Appointment_firstvar1.txt")
  if !counter! equ 125 (echo.%%j>> "%fileno%-Appointment_firstvar1.txt")
  if !counter! equ 126 (echo.%%j>> "%fileno%-Appointment_firstvar1.txt")
  if !counter! equ 128 (echo.%%j> "%fileno%-Appointment_secondvar1.txt")
  if !counter! equ 129 (echo.%%j>> "%fileno%-Appointment_secondvar1.txt")
  if !counter! equ 130 (echo.%%j>> "%fileno%-Appointment_secondvar1.txt")
  if !counter! equ 131 (echo.%%j>> "%fileno%-Appointment_secondvar1.txt")
  if !counter! equ 132 (echo.%%j>> "%fileno%-Appointment_secondvar1.txt")
  if !counter! equ 133 (echo.%%j>> "%fileno%-Appointment_secondvar1.txt")
  if !counter! equ 134 (echo.%%j>> "%fileno%-Appointment_secondvar1.txt")
  if !counter! equ 135 (echo.%%j>> "%fileno%-Appointment_secondvar1.txt")
)
:END
endlocal

color 0E

FOR /F "usebackq tokens=2" %%m IN (%fileno%-Appointment_firstvar1.txt) DO SET firstvar=%%m
set firstvar=%firstvar:~6,6%
echo %firstvar%| findstr /r "^[0-9]*$"
if errorlevel 1 echo "First Variable NOT Number" & start %fileno%-Appointment_Login1.txt & set /p firstvar=Enter First Variable

FOR /F "usebackq tokens=2" %%n IN (%fileno%-Appointment_secondvar1.txt) DO SET secondvar=%%n
set secondvar=%secondvar:~6,6%
echo %secondvar%| findstr /r "^[0-9]*$"
if errorlevel 1 echo "Second Variable NOT Number" & start %fileno%-Appointment_Login1.txt & set /p secondvar=Enter Second Variable

set /p firstvalue=<%fileno%-Appointment_firstvar1.txt
for /f "delims=:" %%a in ('findstr /L /O /N /C:"Father's Name" %fileno%-Appointment_firstvar1.txt') do set firstvalue=%fathername%
for /f "delims=:" %%a in ('findstr /L /O /N /C:"Mother's Name" %fileno%-Appointment_firstvar1.txt') do set firstvalue=%mothername%
for /f "delims=:" %%a in ('findstr /L /O /N /C:"Applicant's Given Name" %fileno%-Appointment_firstvar1.txt') do set firstvalue=%givenname%
for /f "delims=:" %%a in ('findstr /L /O /N /C:"Birth Place" %fileno%-Appointment_firstvar1.txt') do set firstvalue=%birthplace%

set /p secondvalue=<%fileno%-Appointment_secondvar1.txt
for /f "delims=:" %%a in ('findstr /L /O /N /C:"Father's Name" %fileno%-Appointment_secondvar1.txt') do set secondvalue=%fathername%
for /f "delims=:" %%a in ('findstr /L /O /N /C:"Mother's Name" %fileno%-Appointment_secondvar1.txt') do set secondvalue=%mothername%
for /f "delims=:" %%a in ('findstr /L /O /N /C:"Applicant's Given Name" %fileno%-Appointment_secondvar1.txt') do set secondvalue=%givenname%
for /f "delims=:" %%a in ('findstr /L /O /N /C:"Birth Place" %fileno%-Appointment_secondvar1.txt') do set secondvalue=%birthplace%


echo ############################### First Variable = "%firstvar%"
echo ############################### First Value = "%firstvalue%"
echo ############################### Second Variable = "%secondvar%"
echo ############################### Second Value = "%secondvalue%"

echo ############################### First Variable = "%firstvar%" >> %fileno%-report.txt
echo ############################### First Value = "%firstvalue%" >> %fileno%-report.txt
echo ############################### Second Variable = "%secondvar%" >> %fileno%-report.txt
echo ############################### Second Value = "%secondvalue%" >> %fileno%-report.txt

color 0E


:curlGenerateOTP
SET /a try+=1
if /i %try% GTR 4 SET /a _rand=%RANDOM%*100/32768+151 & set /a try=0 & SET socks5=--socks5 103.239.6.%_rand%:1080 --proxy-user danteproxy:dantepass


TITLE IVAC %~n0  ##   STEP1 _ CN : %cn% _ RN:  %rn% _ TRY : %try%
echo ###################### STEP ONE.ONE curl version %cn% _ time %time% _ RN:  %rn% _  TRY : %try% ################## >> %fileno%-report.txt
c:\curl\curl%cn% -v --trace-time -S --connect-timeout 3 -m 4 -b %fileno%_cookie.txt -c %fileno%_cookie.txt %socks5% -d "ImgNum=&fileno=%fileno%&otp=&%firstvar%=%firstvalue%&%secondvar%=%secondvalue%&passport_no=%passport_no%&submit_btn=Generate+OTP" -H "Keep-Alive: 60" -H "Connection: keep-alive" --dump-header %fileno%-headers3.txt --user-agent "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0" --referer http://indianvisa-bangladesh.nic.in/visa/Appointment_Login.jsp http://indianvisa-bangladesh.nic.in/visa/GenerateOTP.jsp -L -o %fileno%-GenerateOTP.txt -w "STEP ONE.ONE GenerateOTP Processing on %time% by %try% \n" 2>> %fileno%-report.txt
echo ********************** STEP ONE.ONE ****** Done by IP %_rand% _ time %time% _ RN:  %rn% _  TRY : %try% ************************* >> %fileno%-report.txt	
echo *********************************************************************************************** >> %fileno%-report.txt

findstr /L /O /N /C:"HTTP/1.1 200 OK" %fileno%-headers3.txt
if /i %ERRORLEVEL% EQU 0 echo ********************** Error Level is %ERRORLEVEL% for 200===GenerateOTP=== & goto GenerateOTP200 

findstr /L /O /N /C:"HTTP/1.1 404 Not Found" %fileno%-headers3.txt
if /i %ERRORLEVEL% EQU 0 goto GenerateOTP 

findstr /L /O /N /C:"HTTP/1.1 408 Request Timeout" %fileno%-headers3.txt
if /i %ERRORLEVEL% EQU 0 goto curlGenerateOTP 

findstr /L /O /N /C:"HTTP/1.1 302 Moved Temporarily" %fileno%-headers3.txt
if /i %ERRORLEVEL% EQU 0 echo ********************** Error Level is %ERRORLEVEL% for 302===GenerateOTP=== & goto GenerateOTP302 

echo ********************** SERVER BUSY === Retry Again ===STEP ONE.ONE=== >> %fileno%-report.txt
if /i %try% EQU 200 set try=0 & goto GenerateOTP
goto GenerateOTP
echo ************************* Technical Problem ***************************** >> %fileno%-report.txt

:GenerateOTP200
findstr /L /O /N /C:"The Problem may be due to 500 Server Error/404 Page Not Found" %fileno%-GenerateOTP.txt
if /i %ERRORLEVEL% EQU 0 echo ======   Error Level is %ERRORLEVEL% for ===500 Server Error/404 Page Not Found=== & goto curlGenerateOTP

findstr /L /O /N /C:"Connection: Close" %fileno%-headers3.txt
if /i %ERRORLEVEL% EQU 0 call :captchaenable & goto curlGenerateOTP

:GenerateOTP302
findstr /L /O /N /C:"Invalid Answer" %fileno%-GenerateOTP.txt
if /i %ERRORLEVEL% EQU 0 echo ======   Error Level is %ERRORLEVEL% for ===Invalid Answer=== & goto GenerateOTP 

findstr /L /O /N /C:"Please Enter valid Passport" %fileno%-GenerateOTP.txt
if /i %ERRORLEVEL% EQU 0 echo ======   Error Level is %ERRORLEVEL% for ===Invalid Passport=== & goto EXIT 

findstr /L /O /N /C:"No more otp can be generated today for this application ID" %fileno%-GenerateOTP.txt
if /i %ERRORLEVEL% EQU 0 echo ======   Error Level is %ERRORLEVEL% for ===No more otp=== can be generated today for this application ID & goto EXIT

findstr /L /O /N /C:"OTP can be generated only after appointment time starts" %fileno%-GenerateOTP.txt
if /i %ERRORLEVEL% EQU 0 echo ======   Error Level is %ERRORLEVEL% for ===OTP can be generated only after appointment time starts=== & timeout 1 & goto GenerateOTP

findstr /L /O /N /C:"Invalid filenumber or OTP or Appointment Already taken" %fileno%-GenerateOTP.txt
if /i %ERRORLEVEL% EQU 0 echo ======   Error Level is %ERRORLEVEL% for ===Invalid filenumber or OTP=== & color 0F & timeout 5 & goto Appointment_Login_otp

findstr /r "%fileno%" %fileno%-GenerateOTP.txt>%fileno%-headers3-temp.txt
echo ********************** Error Level is %ERRORLEVEL% in Generated OTP >> %fileno%-report.txt
if /i %ERRORLEVEL% EQU 1 goto GenerateOTP  
FOR /F "usebackq tokens=9" %%p IN (%fileno%-headers3-temp.txt) DO (
SET bgdnumber=%%p
del %fileno%-headers3-temp.txt
)

echo ********************** "%bgdnumber%" **********************
set otp=%bgdnumber:~0,6%
set otptime=%time%
c:\curl\curl%cn% -v -s -d "fileno=%fileno%&passport_no=%passport_no%&birthdate=%birthdate%&otp=%otp%" http://103.239.6.135/ivac/otp/postdata.php -w "Save OTP to server fileno=%fileno%&otp=%otp% Status \n"
echo ********** Time= %otptime% ********** OTP= "%otp%" **********
c:\curl\curl%cn% http://103.239.6.135/ivac/otp/difftime.php?fileno=%fileno% -o %fileno%-difftime.txt -w "Check difftime Save Status \n"
IF EXIST "%fileno%-difftime.txt" FOR /F %%d IN (%fileno%-difftime.txt) DO SET difftime=%%d
echo ********** Time= %otptime% ###################### OTP= %otp% ********** >> %fileno%-report.txt	
echo ###################### STEP ONE *END* *END* *END* *END* ###################### >> %fileno%-report.txt
echo ###################### STEP ONE *END* *END* *END* *END* ###################### >> %fileno%-report.txt
echo ###################### STEP ONE *END* *END* *END* *END* ###################### >> %fileno%-report.txt
echo.>> %fileno%-report.txt
echo.>> %fileno%-report.txt
echo.>> %fileno%-report.txt
echo.>> %fileno%-report.txt
echo.>> %fileno%-report.txt
goto BeginProcessApptPwd 
echo ************************* Technical Problem ***************************** >> %fileno%-report.txt
=====================================================================================
=====================================================================================
=====================================================================================
=====================================================================================
:BeginProcessApptPwd
echo ###################### STEP PROCESSAPPTPWD *BEGIN* *START* ###################### >> %fileno%-report.txt	
echo ###################### STEP TWO TWO TWO *BEGIN* *START* ###################### >> %fileno%-report.txt	
echo ###################### STEP PROCESSAPPTPWD *BEGIN* *START* ###################### >> %fileno%-report.txt	
set /a try=0
set /a sn=0
SET /a rn=%RANDOM%*20/32768

:ProcessApptPwd
TITLE IVAC %~n0  ##   PROCESSAPPTPWD _ IP : %_rand% _ CN : %cn% _ SN:  %sn% _ TRY : %try%
echo ###################### %sn% Current IP Address %_rand% code is %ImgNum2% ajaxCap %ajaxCap% captchatime %captchatime% ######################

c:\curl\curl%cn% http://103.239.6.135/ivac/otp/difftime.php?fileno=%fileno% -o %fileno%-difftime.txt
IF EXIST "%fileno%-difftime.txt" FOR /F %%d IN (%fileno%-difftime.txt) DO SET difftime=%%d
IF /i %difftime% GTR 300 goto GenerateOTP



:Appointment_Login_pwd
SET /a try+=1
if /i %try% GTR 3 SET /a _rand=%RANDOM%*100/32768+151 & set /a try=0 & SET socks5=--socks5 103.239.6.%_rand%:1080 --proxy-user danteproxy:dantepass

echo ###################### STEP APPOINTMENT_LOGIN2 curl version %cn% _ time %time% _ RN:  %rn% _  TRY : %try% ################## >> %fileno%-report.txt
c:\curl\curl%cn% -v --trace-time -S --connect-timeout 3 -m 5 -b %fileno%_cookie.txt -c %fileno%_cookie.txt %socks5% -H "Keep-Alive: 60" -H "Connection: keep-alive" --dump-header %fileno%-Appointment_headers2.txt --user-agent "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0" --referer http://indianvisa-bangladesh.nic.in/visa/index.html http://indianvisa-bangladesh.nic.in/visa/Appointment_Login.jsp --max-redirs 5 -L -o %fileno%-Appointment_Login2.txt -w "STEP TWO.ONE Appointment_Login PWD Processing on %time% by %try% \n" 2>> %fileno%-report.txt	

findstr /L /O /N /C:"HTTP/1.1 200 OK" %fileno%-Appointment_headers2.txt
if /i %ERRORLEVEL% EQU 0 echo ********************** Error Level is %ERRORLEVEL% for 200===BeginGenerateOTP=== & goto Appointment_Login_pwd200 

findstr /L /O /N /C:"HTTP/1.1 404 Not Found" %fileno%-Appointment_headers2.txt
if /i %ERRORLEVEL% EQU 0 goto BeginGenerateOTP 

findstr /L /O /N /C:"HTTP/1.1 302 Moved Temporarily" %fileno%-Appointment_headers2.txt
if /i %ERRORLEVEL% EQU 0 echo ********************** Error Level is %ERRORLEVEL% for 302===BeginGenerateOTP=== & goto BeginProcessApptPwd 

echo ********************** SERVER BUSY === Retry Again ===STEP TWO.ONE=== >> %fileno%-report.txt
if /i %try% EQU 30 set try=0 & goto BeginGenerateOTP
goto Appointment_Login_pwd
echo ************************* Technical Problem ***************************** >> %fileno%-report.txt

:Appointment_Login_pwd200
findstr /L /O /N /C:"The Problem may be due to 500 Server Error/404 Page Not Found" %fileno%-Appointment_Login2.txt
if /i %ERRORLEVEL% EQU 0 echo ======   Error Level is %ERRORLEVEL% for ===500 Server Error/404 Page Not Found=== & goto Appointment_Login_pwd

findstr /L /O /N /C:"Connection: Close" %fileno%-Appointment_headers2.txt
if /i %ERRORLEVEL% EQU 0 call :captchaenable & goto Appointment_Login_pwd

:checkGenerateOTP
@echo off & setlocal EnableDelayedExpansion
for /F "delims=" %%j in ('type "%fileno%-Appointment_Login2.txt"') do (
  set /A counter+=1
  if !counter! equ 119 (echo.%%j> "%fileno%-Appointment_firstvar2.txt")
  if !counter! equ 120 (echo.%%j>> "%fileno%-Appointment_firstvar2.txt")
  if !counter! equ 121 (echo.%%j>> "%fileno%-Appointment_firstvar2.txt")
  if !counter! equ 122 (echo.%%j>> "%fileno%-Appointment_firstvar2.txt")
  if !counter! equ 123 (echo.%%j>> "%fileno%-Appointment_firstvar2.txt")
  if !counter! equ 124 (echo.%%j>> "%fileno%-Appointment_firstvar2.txt")
  if !counter! equ 125 (echo.%%j>> "%fileno%-Appointment_firstvar2.txt")
  if !counter! equ 126 (echo.%%j>> "%fileno%-Appointment_firstvar2.txt")
  if !counter! equ 128 (echo.%%j> "%fileno%-Appointment_secondvar2.txt")
  if !counter! equ 129 (echo.%%j>> "%fileno%-Appointment_secondvar2.txt")
  if !counter! equ 130 (echo.%%j>> "%fileno%-Appointment_secondvar2.txt")
  if !counter! equ 131 (echo.%%j>> "%fileno%-Appointment_secondvar2.txt")
  if !counter! equ 132 (echo.%%j>> "%fileno%-Appointment_secondvar2.txt")
  if !counter! equ 133 (echo.%%j>> "%fileno%-Appointment_secondvar2.txt")
  if !counter! equ 134 (echo.%%j>> "%fileno%-Appointment_secondvar2.txt")
  if !counter! equ 135 (echo.%%j>> "%fileno%-Appointment_secondvar2.txt")
)
:END
endlocal 

color 0D

FOR /F "usebackq tokens=2" %%m IN (%fileno%-Appointment_firstvar2.txt) DO SET firstvar=%%m
set firstvar=%firstvar:~6,6%
echo %firstvar%| findstr /r "^[0-9]*$"
if errorlevel 1 echo "First Variable NOT Number" & start %fileno%-Appointment_Login2.txt & set /p firstvar=Enter First Variable

FOR /F "usebackq tokens=2" %%n IN (%fileno%-Appointment_secondvar2.txt) DO SET secondvar=%%n
set secondvar=%secondvar:~6,6%
echo %secondvar%| findstr /r "^[0-9]*$"
if errorlevel 1 echo "Second Variable NOT Number" & start %fileno%-Appointment_Login2.txt & set /p secondvar=Enter Second Variable


set /p firstvalue=<%fileno%-Appointment_firstvar2.txt
for /f "delims=:" %%a in ('findstr /L /O /N /C:"Father's Name" %fileno%-Appointment_firstvar2.txt') do set firstvalue=%fathername%
for /f "delims=:" %%a in ('findstr /L /O /N /C:"Mother's Name" %fileno%-Appointment_firstvar2.txt') do set firstvalue=%mothername%
for /f "delims=:" %%a in ('findstr /L /O /N /C:"Applicant's Given Name" %fileno%-Appointment_firstvar2.txt') do set firstvalue=%givenname%
for /f "delims=:" %%a in ('findstr /L /O /N /C:"Birth Place" %fileno%-Appointment_firstvar2.txt') do set firstvalue=%birthplace%

set /p secondvalue=<%fileno%-Appointment_secondvar2.txt
for /f "delims=:" %%a in ('findstr /L /O /N /C:"Father's Name" %fileno%-Appointment_secondvar2.txt') do set secondvalue=%fathername%
for /f "delims=:" %%a in ('findstr /L /O /N /C:"Mother's Name" %fileno%-Appointment_secondvar2.txt') do set secondvalue=%mothername%
for /f "delims=:" %%a in ('findstr /L /O /N /C:"Applicant's Given Name" %fileno%-Appointment_secondvar2.txt') do set secondvalue=%givenname%
for /f "delims=:" %%a in ('findstr /L /O /N /C:"Birth Place" %fileno%-Appointment_secondvar2.txt') do set secondvalue=%birthplace%


echo First Variable = "%firstvar%"
echo First Value = "%firstvalue%"
echo Second Variable = "%secondvar%"
echo Second Value = "%secondvalue%"

echo First Variable = "%firstvar%" >> %fileno%-report.txt
echo First Value = "%firstvalue%" >> %fileno%-report.txt
echo Second Variable = "%secondvar%" >> %fileno%-report.txt
echo Second Value = "%secondvalue%" >> %fileno%-report.txt

color 0D


:otpcaptcha
if /i %cap% EQU 4 SET ImgNum2=& goto curlProcessApptPwd
color A9 
TITLE IVAC %~n0  ##   OTPCAPTCHA _  OTP= %otp% _ Time= %otptime% _ TRY : %try% _ IP : %_rand% _ CN : %cn%
SET /a try+=1
if /i %try% GTR 3 SET /a _rand=%RANDOM%*100/32768+151 & set /a try=0 & SET socks5=--socks5 103.239.6.%_rand%:1080 --proxy-user danteproxy:dantepass

SET /a cn=%RANDOM%*8/32768
echo curl version %cn%

c:\curl\curl%cn% -v --trace-time -S --connect-timeout 3 -m 5 -b %fileno%_cookie.txt -c %fileno%_cookie.txt %socks5% --dump-header %fileno%-headers11.txt --user-agent "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0" --referer http://indianvisa-bangladesh.nic.in/visa/ReprintAppt.jsp http://indianvisa-bangladesh.nic.in/visa/Rimage.jsp -o %fileno%-captcha.jpg -w "STEP OTPCAPTCHA CAPTCHA Processing on %time% by %try% \n" 2>> %fileno%-report.txt
echo ********************** STEP OTPCAPTCHA ****** Done by IP %_rand% _ time %time% _ SN:  %sn% _  TRY : %try% ************************* >> %fileno%-report.txt	

findstr /L /O /N /C:"Content-Type: text/html" %fileno%-headers11.txt
if /i %ERRORLEVEL% EQU 0 call :captchaenable & goto otpcaptcha 

findstr /L /O /N /C:"Content-Type: image/jpeg" %fileno%-headers11.txt
if /i %ERRORLEVEL% EQU 0 echo **********************   Error Level is %ERRORLEVEL% for ===STEP OTPCAPTCHA=== & goto retriveotpcode 

echo ********************** SERVER BUSY === Retry Again ===STEP OTPCAPTCHA=== >> %fileno%-report.txt
goto otpcaptcha

:retriveotpcode 
color A4
echo ####### Start FC on time %time% ####### %ImgNum1% ####### %ImgNum2% ####### %ImgNum3% ####### %ImgNum% ####### >> %fileno%-report.txt
c:\curl\curl -S -F "source_url=" -F "captcha_platform=" -F "action=Submit" -F "file=@%fileno%-captcha.jpg" http://103.239.6.141/gsa_test.gsa -o %fileno%-code.txt
FOR /F "tokens=11 delims=<\/>" %%m IN (%fileno%-code.txt) DO del %fileno%-captcha.jpg & SET ImgNum2=%%m
echo ####### End FC on time %time% ####### %ImgNum1% ####### %ImgNum2% ####### %ImgNum3% ####### %ImgNum% ####### >> %fileno%-report.txt

set try=0

rem set ImgNum2=
rem remove from otpcaptcha then 424 to 452 you can enable ImgNum2

echo First Variable = "%firstvar%" >> %fileno%-report.txt	
echo First Value = "%firstvalue%" >> %fileno%-report.txt	
echo Second Variable = "%secondvar%" >> %fileno%-report.txt	
echo Second Value = "%secondvalue%" >> %fileno%-report.txt	
echo OTP = "%otp%" >> %fileno%-report.txt	
echo ImgNum = "%ImgNum2%" >> %fileno%-report.txt	


:curlProcessApptPwd
color EC
SET /a try+=1
if /i %try% GTR 3 SET /a _rand=%RANDOM%*100/32768+151 & set /a try=0 & SET socks5=--socks5 103.239.6.%_rand%:1080 --proxy-user danteproxy:dantepass

TITLE IVAC %~n0  ##   STEP2 _  OTP= %otp% _ Time= %time% _ TRY : %try% _ IP : %_rand% _ CN : %cn%
echo ###################### STEP TWO.TWO curl version %cn% IP %_rand% _ time %time% _ SN:  %sn% _  TRY : %try% ################## >> %fileno%-report.txt	
c:\curl\curl%cn% -v --trace-time --retry 2 --retry-delay 1 -S --connect-timeout 3 -m 5 -b %fileno%_cookie.txt -c %fileno%_cookie.txt %socks5% -d "ImgNum=%ImgNum2%&fileno=%fileno%&otp=%otp%&%firstvar%=%firstvalue%&%secondvar%=%secondvalue%&passport_no=%passport_no%&submit_btn=Submit" -H "Keep-Alive: 60" -H "Connection: keep-alive" --dump-header %fileno%-headers5.txt --user-agent "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0" --referer http://indianvisa-bangladesh.nic.in/visa/Appointment_Home.jsp http://indianvisa-bangladesh.nic.in/visa/ProcessApptPwd.jsp -o %fileno%-ProcessApptPwd.txt -w "STEP TWO.TWO ProcessApptPwd Processing on %time% by %try% \n" 2>> %fileno%-report.txt	
echo ********************** STEP TWO.TWO ****** Done by IP %_rand% _ time %time% _ SN:  %sn% _  TRY : %try% ************************* >> %fileno%-report.txt	
echo *********************************************************************************************** >> %fileno%-report.txt	

findstr /L /O /N /C:"HTTP/1.1 200 OK" %fileno%-headers5.txt
if /i %ERRORLEVEL% EQU 0 echo ********************** Error Level is %ERRORLEVEL% for 200===Appointment_Home=== & goto ProcessApptPwd200 

findstr /L /O /N /C:"HTTP/1.1 302 Moved Temporarily" %fileno%-headers5.txt
if /i %ERRORLEVEL% EQU 0 echo ======   Error Level is %ERRORLEVEL% for ===Captcha OK=== & goto ProcessApptPwd302 

echo ********************** SERVER BUSY === Retry Again ===STEP TWO.TWO=== >> %fileno%-report.txt
if /i %try% EQU 20 set try=0 & goto ProcessApptPwd
goto curlProcessApptPwd
echo ************************* Technical Problem ***************************** >> %fileno%-report.txt	

:ProcessApptPwd200
findstr /L /O /N /C:"Invalid Answer" %fileno%-ProcessApptPwd.txt
if /i %ERRORLEVEL% EQU 0 echo ======   Error Level is %ERRORLEVEL% for Invalid Answer & goto ProcessApptPwd 

findstr /L /O /N /C:"Invalid filenumber or OTP or Appointment Already taken" %fileno%-ProcessApptPwd.txt
if /i %ERRORLEVEL% EQU 0 echo ======   Error Level is %ERRORLEVEL% for Please generate OTP & goto EXIT 

findstr /L /O /N /C:"Your OTP is expired" %fileno%-ProcessApptPwd.txt
if /i %ERRORLEVEL% EQU 0 echo ======   Error Level is %ERRORLEVEL% for Please generate OTP & goto GenerateOTP 

findstr /L /O /N /C:"Please generate OTP" %fileno%-ProcessApptPwd.txt
if /i %ERRORLEVEL% EQU 0 echo ======   Error Level is %ERRORLEVEL% for ===Please generate OTP=== & goto curlProcessApptPwd

findstr /L /O /N /C:"Invalid OTP. Please try again" %fileno%-ProcessApptPwd.txt
if /i %ERRORLEVEL% EQU 0 echo ======   Error Level is %ERRORLEVEL% for ===Invalid OTP. Please try again=== & goto curlProcessApptPwd

findstr /L /O /N /C:"The Problem may be due to 500 Server Error/404 Page Not Found" %fileno%-ProcessApptPwd.txt
if /i %ERRORLEVEL% EQU 0 echo ======   Error Level is %ERRORLEVEL% for ===500 Server Error/404 Page Not Found=== & goto curlProcessApptPwd

findstr /L /O /N /C:"Connection: Close" %fileno%-headers5.txt
if /i %ERRORLEVEL% EQU 0 call :captchaenable & goto curlProcessApptPwd

findstr /r "Transfer-Encoding: chunked" %fileno%-headers5.txt
if /i %ERRORLEVEL% EQU 0 goto BeginAppointment_Passport
echo ************************* Technical Problem ***************************** >> %fileno%-report.txt	


:ProcessApptPwd302
findstr /L /O /N /C:"Invalid Answer" %fileno%-headers5.txt
if /i %ERRORLEVEL% EQU 0 echo ======   Error Level is %ERRORLEVEL% for Invalid Answer & goto ProcessApptPwd 

findstr /L /O /N /C:"Invalid OTP" %fileno%-headers5.txt
if /i %ERRORLEVEL% EQU 0 echo ======   Error Level is %ERRORLEVEL% for Invalid Answer & goto ProcessApptPwd 

findstr /L /O /N /C:"Please generate OTP" %fileno%-headers5.txt
if /i %ERRORLEVEL% EQU 0 echo ======   Error Level is %ERRORLEVEL% for Please generate OTP & goto GenerateOTP 

findstr /L /O /N /C:"Invalid filenumber or OTP or Appointment Already taken" %fileno%-headers5.txt
if /i %ERRORLEVEL% EQU 0 echo ======   Error Level is %ERRORLEVEL% for Please generate OTP & goto EXIT 

findstr /L /O /N /C:"Your OTP is expired" %fileno%-headers5.txt
if /i %ERRORLEVEL% EQU 0 echo ======   Error Level is %ERRORLEVEL% for Please generate OTP & goto GenerateOTP 

findstr /L /O /N /C:"indianvisa-bangladesh.nic.in/visa/index.html" %fileno%-headers5.txt
if /i %ERRORLEVEL% EQU 0 echo ======   Error Level is %ERRORLEVEL% for Please generate OTP & goto ProcessApptPwd 

findstr /r "Appointment_Home" %fileno%-headers5.txt
echo ********************** Error Level is %ERRORLEVEL% in Appointment Home >> %fileno%-report.txt
rem del %fileno%-headers2.txt
echo ###################### STEP TWO *END* *END* *END* *END* ###################### >> %fileno%-report.txt	
echo ###################### STEP TWO *END* *END* *END* *END* ###################### >> %fileno%-report.txt	
echo ###################### STEP TWO *END* *END* *END* *END* ###################### >> %fileno%-report.txt	
echo.>> %fileno%-report.txt	
echo.>> %fileno%-report.txt	
echo.>> %fileno%-report.txt	
echo.>> %fileno%-report.txt	
echo.>> %fileno%-report.txt	

set /a try=0
if /i %ERRORLEVEL% EQU 0 goto BeginAppointment_Passport
=====================================================================================
=====================================================================================
=====================================================================================
=====================================================================================
:BeginAppointment_Passport
echo ###################### STEP APPOINTMENT_PASSPORT *BEGIN* *START* ###################### >> %fileno%-report.txt	
echo ###################### STEP THREE THREE THREE *BEGIN* *START* ###################### >> %fileno%-report.txt	
echo ###################### STEP APPOINTMENT_PASSPORT *BEGIN* *START* ###################### >> %fileno%-report.txt	
set /a try=0
set /a sn=0


:Appointment_Passport
color 21 
TITLE IVAC %~n0  ##   APPOINTMENT_PASSPORT _  OTP= %otp% _ Time= %otptime% _ TRY : %try% _ IP : %_rand% _ CN : %cn%

:curlAppointment_Passport
SET /a try+=1
if /i %try% GTR 3 SET /a _rand=%RANDOM%*100/32768+151 & set /a try=0 & SET socks5=--socks5 103.239.6.%_rand%:1080 --proxy-user danteproxy:dantepass

TITLE IVAC %~n0  ##   APPOINTMENT_PASSPORT _  OTP= %otp% _ Time= %otptime% _ TRY : %try% _ IP : %_rand% _ CN : %cn%
echo ###################### STEP THREE.THREE curl version %cn% IP %_rand% _ time %time% _ SN:  %sn% _  TRY : %try% ################## >> %fileno%-report.txt	
c:\curl\curl%cn% -v --trace-time --retry 2 --retry-delay 1 -S --connect-timeout 3 -m 5 -b %fileno%_cookie.txt -c %fileno%_cookie.txt %socks5% -d "ImgNum=%ImgNum2%&birthdate=%birthdate%&fileno=%fileno%&pia=%pia1%&submit_btn=Submit" --dump-header %fileno%-headers6.txt --user-agent "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0" --referer http://indianvisa-bangladesh.nic.in/visa/Appointment_Home.jsp http://indianvisa-bangladesh.nic.in/visa/Appointment_Passport.jsp -o %fileno%-Appointment_Passport.txt -w "STEP THREE.THREE Appointment_Home Processing on %time% by %try% \n" 2>> %fileno%-report.txt	
echo ************************* STEP THREE.THREE ****** Done by IP %_rand% _ time %time% _ SN:  %sn% _  TRY : %try% ************************* >> %fileno%-report.txt	
echo *********************************************************************************************** >> %fileno%-report.txt	

findstr /L /O /N /C:"HTTP/1.1 200 OK" %fileno%-headers6.txt
if /i %ERRORLEVEL% EQU 0 echo ********************** Error Level is %ERRORLEVEL% for 200===Appointment_Home=== & goto Appointment_Passport200 

findstr /L /O /N /C:"HTTP/1.1 302 Moved Temporarily" %fileno%-headers6.txt
if /i %ERRORLEVEL% EQU 0 echo ********************** Error Level is %ERRORLEVEL% for 302===Appointment_Home=== & goto Appointment_Passport302 

echo ********************** SERVER BUSY === Retry Again ===STEP THREE.THREE=== >> %fileno%-report.txt
goto Appointment_Passport


:Appointment_Passport302
findstr /L /O /N /C:"Invalid Captcha" %fileno%-headers6.txt
if /i %ERRORLEVEL% EQU 0 echo ======   Error Level is %ERRORLEVEL% for ===Invalid Answer=== & goto ProcessApptPwd 

findstr /L /O /N /C:"Invalid File Number or Date of birth or Mission" %fileno%-headers6.txt
if /i %ERRORLEVEL% EQU 0 echo ======   Error Level is %ERRORLEVEL% for ===Invalid Answer=== & goto GenerateOTP 

findstr /L /O /N /C:"Your OTP is expired" %fileno%-headers6.txt
if /i %ERRORLEVEL% EQU 0 echo ======   Error Level is %ERRORLEVEL% for ===Invalid Answer=== & goto StartBegin 

findstr /r "Appointment_Login" %fileno%-headers6.txt
if /i %ERRORLEVEL% EQU 0 goto GenerateOTP

:Appointment_Passport200
findstr /L /O /N /C:"The Problem may be due to 500 Server Error/404 Page Not Found" %fileno%-Appointment_Passport.txt
if /i %ERRORLEVEL% EQU 0 echo ======   Error Level is %ERRORLEVEL% for ===The Problem may be due to 500 Server Error/404 Page Not Found=== & goto Appointment_Passport

findstr /L /O /N /C:"Access code is not valid" %fileno%-Appointment_Passport.txt
if /i %ERRORLEVEL% EQU 0 echo ======   Error Level is %ERRORLEVEL% for ===Access code is not valid=== & goto EXIT

findstr /L /O /N /C:"Connection: Close" %fileno%-headers6.txt
if /i %ERRORLEVEL% EQU 0 call :captchaenable & goto Appointment_Passport

echo ###################### STEP THREE *END* *END* *END* *END* ###################### >> %fileno%-report.txt	
echo ###################### STEP THREE *END* *END* *END* *END* ###################### >> %fileno%-report.txt	
echo ###################### STEP THREE *END* *END* *END* *END* ###################### >> %fileno%-report.txt	
echo.>> %fileno%-report.txt	
echo.>> %fileno%-report.txt	
echo.>> %fileno%-report.txt	
echo.>> %fileno%-report.txt	
echo.>> %fileno%-report.txt	
findstr /r "Transfer-Encoding: chunked" %fileno%-headers6.txt
if /i %ERRORLEVEL% EQU 0 goto BeginReprintAppt
echo ************************* Technical Problem ***************************** >> %fileno%-report.txt	
=====================================================================================
=====================================================================================
=====================================================================================
=====================================================================================
:BeginReprintAppt
echo ###################### STEP REPRINTAPPT *BEGIN* *START* ###################### >> %fileno%-report.txt	
echo ###################### STEP FOUR FOUR FOUR *BEGIN* *START* ###################### >> %fileno%-report.txt	
echo ###################### STEP REPRINTAPPT *BEGIN* *START* ###################### >> %fileno%-report.txt	
set /a try=0
set /a sn=0

:choosepath
if %ImgNum2%==[%1]==[] goto reprintappt_captcha
goto ReprintAppt

:reprintappt_captcha
color A9 
TITLE IVAC %fileno% REPRINTAPPT_CAPTCHA _  OTP= %otp% _ Time= %otptime% _ TRY : %try% _ IP : %_rand% _ CN : %cn%
SET /a try+=1
if /i %try% GTR 3 SET /a _rand=%RANDOM%*100/32768+151 & set /a try=0 & SET socks5=--socks5 103.239.6.%_rand%:1080 --proxy-user danteproxy:dantepass

SET /a cn=%RANDOM%*8/32768
echo curl version %cn%
c:\curl\curl%cn% -v --trace-time -S --connect-timeout 3 -m 5 -b %fileno%_cookie.txt -c %fileno%_cookie.txt %socks5% --dump-header %fileno%-headers13.txt --user-agent "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0" --referer http://indianvisa-bangladesh.nic.in/visa/ReprintAppt.jsp http://indianvisa-bangladesh.nic.in/visa/Rimage.jsp -o %fileno%-captcha.jpg -w "STEP REPRINTAPPT_CAPTCHA CAPTCHA Processing on %time% by %try% \n" 2>> %fileno%-report.txt
echo ********************** STEP REPRINTAPPT_CAPTCHA ****** Done by IP %_rand% _ time %time% _ SN:  %sn% _  TRY : %try% ************************* >> %fileno%-report.txt	

if /i %try% EQU 20 SET /a _rand=%RANDOM%*100/32768+151 & set try=0

findstr /L /O /N /C:"Content-Type: text/html" %fileno%-headers13.txt
if /i %ERRORLEVEL% EQU 0 call :captchaenable & goto reprintappt_captcha 

findstr /L /O /N /C:"Content-Type: image/jpeg" %fileno%-headers13.txt
if /i %ERRORLEVEL% EQU 0 echo **********************   Error Level is %ERRORLEVEL% for ===STEP REPRINTAPPT_CAPTCHA=== & goto retrivecode1 

echo ********************** SERVER BUSY === Retry Again ===STEP REPRINTAPPT_CAPTCHA=== >> %fileno%-report.txt
goto reprintappt_captcha

:retrivecode1 
color A4
echo ####### Start FC on time %time% ####### %ImgNum1% ####### %ImgNum2% ####### %ImgNum3% ####### %ImgNum% ####### >> %fileno%-report.txt
c:\curl\curl -S -F "source_url=" -F "captcha_platform=" -F "action=Submit" -F "file=@%fileno%-captcha.jpg" http://103.239.6.141/gsa_test.gsa -o %fileno%-code.txt
FOR /F "tokens=11 delims=<\/>" %%m IN (%fileno%-code.txt) DO del %fileno%-captcha.jpg & SET ImgNum2=%%m
echo ####### End FC on time %time% ####### %ImgNum1% ####### %ImgNum2% ####### %ImgNum3% ####### %ImgNum% ####### >> %fileno%-report.txt

set try=0

:ReprintAppt
color 21 
TITLE IVAC %fileno% STEP4_REPRINTAPPT _  OTP= %otp% _ Time= %otptime% _ TRY : %try% _ IP : %_rand% _ CN : %cn%
SET /a try+=1
if /i %try% GTR 3 SET /a _rand=%RANDOM%*100/32768+151 & set /a try=0 & SET socks5=--socks5 103.239.6.%_rand%:1080 --proxy-user danteproxy:dantepass

echo ###################### STEP FOUR.FOUR curl version %cn% IP %_rand% _ time %time% _ SN:  %sn% _  TRY : %try% ################## >> %fileno%-report.txt	
c:\curl\curl%cn% -v --trace-time --retry 2 --retry-delay 1 -S --connect-timeout 3 -m 5 -b %fileno%_cookie.txt -c %fileno%_cookie.txt %socks5% -d "ImgNum=%ImgNum2%&fileno=%fileno%&passport_no=%passport_no%&submit_btn=Submit" --dump-header %fileno%-headers8.txt --user-agent "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0" --referer http://indianvisa-bangladesh.nic.in/visa/Appointment_Passport.jsp http://indianvisa-bangladesh.nic.in/visa/ReprintAppt.jsp -o %fileno%-ReprintAppt.txt -w "STEP FOUR.FOUR Appointment_Home Processing on %time% by %try% \n" 2>> %fileno%-report.txt	
echo ************************* STEP FOUR.FOUR ****** Done by IP %_rand% _ time %time% _ SN:  %sn% _  TRY : %try% ************************* >> %fileno%-report.txt	
echo *********************************************************************************************** >> %fileno%-report.txt	

findstr /L /O /N /C:"HTTP/1.1 200 OK" %fileno%-headers8.txt
if /i %ERRORLEVEL% EQU 0 echo ********************** Error Level is %ERRORLEVEL% for 200===Appointment_Home=== & goto ReprintAppt200 

findstr /L /O /N /C:"HTTP/1.1 302 Moved Temporarily" %fileno%-headers8.txt
if /i %ERRORLEVEL% EQU 0 echo ********************** Error Level is %ERRORLEVEL% for 302===Appointment_Home=== & goto ReprintAppt302 

echo ********************** SERVER BUSY === Retry Again ===STEP FOUR.FOUR=== >> %fileno%-report.txt
goto ReprintAppt


:ReprintAppt302
findstr /L /O /N /C:"Invalid Captcha" %fileno%-headers8.txt
if /i %ERRORLEVEL% EQU 0 echo ======   Error Level is %ERRORLEVEL% for ===Invalid Answer=== & goto ProcessApptPwd 

findstr /L /O /N /C:"Invalid Filenumber" %fileno%-headers8.txt
if /i %ERRORLEVEL% EQU 0 echo ======   Error Level is %ERRORLEVEL% for ===Invalid Filenumber=== & goto GenerateOTP 

findstr /L /O /N /C:"Your OTP is expired" %fileno%-headers8.txt
if /i %ERRORLEVEL% EQU 0 echo ======   Error Level is %ERRORLEVEL% for ===Invalid Answer=== & goto GenerateOTP 

findstr /r "Appointment_Login" %fileno%-headers8.txt
if /i %ERRORLEVEL% EQU 0 goto GenerateOTP

findstr /r "no_appointment_dates" %fileno%-headers8.txt
if /i %ERRORLEVEL% EQU 0 goto EXIT
rem no_appointment_dates == goto EXIT	ReprintAppt


:ReprintAppt200
findstr /L /O /N /C:"New Appointment is possible only" %fileno%-ReprintAppt.txt
if /i %ERRORLEVEL% EQU 0 echo ======   Error Level is %ERRORLEVEL% for ===New Appointment is possible only within 5 days of Registration's Date=== & goto EXIT

findstr /L /O /N /C:"Appointment Date is already taken" %fileno%-ReprintAppt.txt
if /i %ERRORLEVEL% EQU 0 echo ======   Error Level is %ERRORLEVEL% for ===Appointment Date is already taken=== & goto EXIT

findstr /L /O /N /C:"Access code is not valid" %fileno%-ReprintAppt.txt
if /i %ERRORLEVEL% EQU 0 echo ======   Error Level is %ERRORLEVEL% for ===Access code is not valid=== & goto reprintappt_captcha

findstr /L /O /N /C:"The Problem may be due to 500 Server Error/404 Page Not Found.Please contact your system administrator" %fileno%-ReprintAppt.txt
if /i %ERRORLEVEL% EQU 0 echo ======   Error Level is %ERRORLEVEL% for ===The Problem may be due to 500 Server Error/404 Page Not Found.=== & goto ReprintAppt

findstr /L /O /N /C:"%fileno%" %fileno%-ReprintAppt.txt
if /i %ERRORLEVEL% EQU 0 echo ======   Error Level is %ERRORLEVEL% for ===RetriveReprintAppt=== & goto RetriveReprintAppt

findstr /L /O /N /C:"Connection: Close" %fileno%-headers8.txt
if /i %ERRORLEVEL% EQU 0 call :captchaenable & goto ReprintAppt

findstr /r "Transfer-Encoding: chunked" %fileno%-headers8.txt
if /i %ERRORLEVEL% EQU 0 set try=0 & goto RetriveReprintAppt


=============================================================================================
:RetriveReprintAppt
findstr /c:"select name" %fileno%-ReprintAppt.txt > %fileno%-datevar.txt
FOR /F "usebackq tokens=2" %%m IN (%fileno%-datevar.txt) DO SET datevar=%%m
set datevar=%datevar:~6,6%
echo %datevar%| findstr /r "^[0-9]*$"
if errorlevel 1 echo "Date Variable NOT Number" & start %fileno%-ReprintAppt.txt & set /p datevar=Enter Date Variable

findstr /c:"input type=\"text\"" %fileno%-ReprintAppt.txt > %fileno%-otpvar.txt
FOR /F "usebackq tokens=5" %%n IN (%fileno%-otpvar.txt) DO SET otpvar=%%n
set otpvar=%otpvar:~6,6%
echo %otpvar%| findstr /r "^[0-9]*$"
if errorlevel 1 echo "OTP Variable NOT Number" & start %fileno%-ReprintAppt.txt & set /p otpvar=Enter OTP Variable

echo ################################################ >> %fileno%-report.txt
echo "%datevar%=%aptdate%" >> %fileno%-report.txt
echo "%otpvar%=%otp%" >> %fileno%-report.txt
echo ################################################ >> %fileno%-report.txt


goto final
=============================================================================================


:getFilesize
set filesize=%~z1
exit /b



:captchaenable
echo ************************* captcha enable on time %time% ************************* >> %fileno%-report.txt
c:\curl\curl%cn% -v --trace-time --retry 2 --retry-delay 1 -S -m 5 -b %fileno%_cookie.txt -c %fileno%_cookie.txt %socks5% -H "Keep-Alive: 60" -H "Connection: keep-alive" --dump-header %fileno%-headers5.txt --user-agent "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0" --referer http://indianvisa-bangladesh.nic.in/visa/ReprintAppt.jsp http://indianvisa-bangladesh.nic.in/captcha.gif -o %fileno%-captcha.gif -w "CAPTCHA ENABLED on %time% by %try% \n" 2>> %fileno%-report.txt
echo ************************* captcha done on time %time% ************************* >> %fileno%-report.txt	

rem set /a try +=1
rem if /i %try% EQU 5 SET /a _rand=%RANDOM%*100/32768+151 & set try=0


rem set /p code=Enter Captcha Code:  
c:\curl\curl -S -F "source_url=" -F "captcha_platform=" -F "action=Submit" -F "file=@%fileno%-captcha.gif"  --dump-header %fileno%-headers7.txt --user-agent "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0"   http://103.239.6.142/gsa_test.gsa -o %fileno%-gif.txt  

FOR /F "tokens=11 delims=<\/>" %%l IN (%fileno%-gif.txt) DO del %fileno%-captcha.gif & SET code2=%%l
set try=0
echo ###################### STEP CAPTCHA ****** Result is %code2% on time %time% ###################### >> %fileno%-report.txt	
echo ######################### ====== %code2% ====== #########################


:captchacode
SET /a try+=1
if /i %try% GTR 3 SET /a _rand=%RANDOM%*100/32768+151 & set /a try=0 & SET socks5=--socks5 103.239.6.%_rand%:1080 --proxy-user danteproxy:dantepass

c:\curl\curl%cn% -v --trace-time -i --retry 2 --retry-delay 1 -S -m 5 -b %fileno%_cookie.txt -c %fileno%_cookie.txt %socks5% -H "Keep-Alive: 60" -H "Connection: keep-alive" -d "captcha_resp_txt=%code2%" --dump-header %fileno%-headers9.txt --user-agent "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0" --referer http://indianvisa-bangladesh.nic.in/visa/ http://indianvisa-bangladesh.nic.in/captcha_resp -o %fileno%-captcha.done -w "CAPTCHA DONE on %time% by %try% \n" 2>> %fileno%-report.txt	
echo ************************* captcha code for captcha_resp on time %time% ************************* >> %fileno%-report.txt	

rem set /a try +=1
rem if /i %try% EQU 20 SET /a _rand=%RANDOM%*100/32768+151 & set try=0 & goto captchaenable

findstr /L /O /N /C:"HTTP/1.1 200 OK" %fileno%-headers9.txt
if /i %ERRORLEVEL% EQU 0 goto captchaenable

findstr /L /O /N /C:"HTTP/1.1 404 Not Found" %fileno%-headers9.txt
if /i %ERRORLEVEL% EQU 0 goto captchaenable

findstr /L /O /N /C:"HTTP/1.1 302 Redirect" %fileno%-headers9.txt
if /i %ERRORLEVEL% EQU 1 goto captchacode

rem copy %fileno%_cookie.txt %fileno%_cookie.txt
copy %fileno%_cookie.txt otpcookie%rn%.txt
IF EXIST "%fileno%-captcha.done" del %fileno%-captcha.done

echo ************************* STEP CAPTCHA captcha_resp done on time %time% ************************* >> %fileno%-report.txt	
echo ************************* STEP CAPTCHA captcha_resp done on time %time% ************************* >> %fileno%-report.txt	

exit /b






:final
color A9 
TITLE IVAC %~n0  ##   FINAL _  OTP= %otp% _ Time= %otptime% _ TRY : %try% _ IP : %_rand% _ CN : %cn%
SET /a try+=1
if /i %try% GTR 3 SET /a _rand=%RANDOM%*100/32768+151 & set /a try=0 & SET socks5=--socks5 103.239.6.%_rand%:1080 --proxy-user danteproxy:dantepass

SET /a cn=%RANDOM%*8/32768
echo curl version %cn%

c:\curl\curl%cn% -v --trace-time -S --connect-timeout 3 -m 5 -b %fileno%_cookie.txt -c %fileno%_cookie.txt %socks5% --dump-header %fileno%-headers11.txt --user-agent "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0" --referer http://indianvisa-bangladesh.nic.in/visa/ReprintAppt.jsp http://indianvisa-bangladesh.nic.in/visa/Rimage.jsp -o %fileno%-captcha.jpg -w "STEP FINAL CAPTCHA Processing on %time% by %try% \n" 2>> %fileno%-report.txt
echo ********************** STEP FINAL ****** Done by IP %_rand% _ time %time% _ SN:  %sn% _  TRY : %try% ************************* >> %fileno%-report.txt	

findstr /L /O /N /C:"Content-Type: text/html" %fileno%-headers11.txt
if /i %ERRORLEVEL% EQU 0 call :captchaenable & goto final 

findstr /L /O /N /C:"Content-Type: image/jpeg" %fileno%-headers11.txt
if /i %ERRORLEVEL% EQU 0 echo **********************   Error Level is %ERRORLEVEL% for ===STEP FINAL=== & goto retrivecode 

echo ********************** SERVER BUSY === Retry Again ===STEP FINAL=== >> %fileno%-report.txt
goto final

:retrivecode 
color A4
echo ####### Start FC on time %time% ####### %ImgNum1% ####### %ImgNum2% ####### %ImgNum3% ####### %ImgNum% ####### >> %fileno%-report.txt
c:\curl\curl -S -F "source_url=" -F "captcha_platform=" -F "action=Submit" -F "file=@%fileno%-captcha.jpg" http://103.239.6.140/gsa_test.gsa -o %fileno%-code.txt
FOR /F "tokens=11 delims=<\/>" %%m IN (%fileno%-code.txt) DO del %fileno%-captcha.jpg & SET ImgNum=%%m
echo ####### End FC on time %time% ####### %ImgNum1% ####### %ImgNum2% ####### %ImgNum3% ####### %ImgNum% ####### >> %fileno%-report.txt

set try=0

echo ################################################ >> %fileno%-report.txt
echo "fileno=%fileno%" >> %fileno%-report.txt
echo "APPLNAME=%APPLNAME%" >> %fileno%-report.txt
echo "PIA=%pia%" >> %fileno%-report.txt
echo "%datevar%=%aptdate%" >> %fileno%-report.txt
echo "%otpvar%=%otp%" >> %fileno%-report.txt
echo "ImgNum=%ImgNum%" >> %fileno%-report.txt
echo ################################################ >> %fileno%-report.txt


:postdata 
color 09 
TITLE IVAC %~n0  ##   POSTDATA _  OTP= %otp% _ Time= %otptime% _ APPLNAME : %APPLNAME%

echo =================== IP:  %_rand% =================== Retry: %try% =================== >> %fileno%-report.txt	
	
echo curl version %cn%
SET /a try+=1
if /i %try% GTR 3 SET /a _rand=%RANDOM%*100/32768+151 & set /a try=0 & SET socks5=--socks5 103.239.6.%_rand%:1080 --proxy-user danteproxy:dantepass

c:\curl\curl%cn%  -v --trace-time -S -m 5 -b %fileno%_cookie.txt -c %fileno%_cookie.txt %socks5% -d "fileno=%fileno%&APPLNAME=%APPLNAME%&PIA=%pia%&next_page=Visa_print_Form2.jsp&%datevar%=%aptdate%&%otpvar%=%otp%&ImgNum=%ImgNum%&SAVE=Confirm+The+Appointment" --dump-header %fileno%-headers12.txt --user-agent "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0" --referer http://indianvisa-bangladesh.nic.in/visa/ReprintAppt.jsp http://indianvisa-bangladesh.nic.in/visa/allotmentsave.jsp -o %fileno%-allotmentsave.txt 2>> %fileno%-report.txt	
 
if /i %try% EQU 20 SET /a _rand=%RANDOM%*100/32768+151 & set try=0

findstr /L /O /N /C:"HTTP/1.1 200 OK" %fileno%-headers12.txt
if /i %ERRORLEVEL% EQU 0 echo ********************** Error Level is %ERRORLEVEL% for 200===allotmentsave=== & goto checkfinal200 

findstr /L /O /N /C:"HTTP/1.1 302 Moved Temporarily" %fileno%-headers12.txt
if /i %ERRORLEVEL% EQU 0 echo ********************** Error Level is %ERRORLEVEL% for 302===allotmentsave=== & goto checkfinal302 

echo ********************** SERVER BUSY === Retry Again ===STEP POSTDATA=== >> %fileno%-report.txt
goto postdata

:checkfinal302
findstr /L /O /N /C:"Invalid Captcha" %fileno%-headers12.txt
if /i %ERRORLEVEL% EQU 0 echo ======   Error Level is %ERRORLEVEL% for ===Invalid Answer=== & goto EXIT 

findstr /r "indianVisaReg" %fileno%-headers12.txt
if /i %ERRORLEVEL% EQU 0 goto EXIT

findstr /r "Visa_print_Form2.jsp?number=%fileno%" %fileno%-headers12.txt
if /i %ERRORLEVEL% EQU 0 (
c:\curl\curl%cn% -v -s -d "fileno=%fileno%&passport_no=%passport_no%&birthdate=%birthdate%&APPLNAME=%APPLNAME%" http://103.239.6.135/ivac/allotmentsave/postdata.php
goto EXIT
)

:checkfinal200
findstr /L /O /N /C:"The Problem may be due to 500 Server Error/404 Page Not Found" %fileno%-allotmentsave.txt
if /i %ERRORLEVEL% EQU 0 echo ======   Error Level is %ERRORLEVEL% for ===The Problem may be due to 500 Server Error/404 Page Not Found=== & goto postdata

findstr /L /O /N /C:"Connection: Close" %fileno%-headers12.txt
if /i %ERRORLEVEL% EQU 0 call :captchaenable & goto postdata

	
:EXIT	
echo =================== *********************************************** =================== >> %fileno%-report.txt	
echo =================== ************* END OF CURL EXECUTE ************* =================== >> %fileno%-report.txt	
echo =================== *********************************************** =================== >> %fileno%-report.txt	
echo. >> %fileno%-report.txt	
echo. >> %fileno%-report.txt	
echo Sucess 
pause
rem start %fileno%_bgdfinal.bat 	

